# Generated by Django 4.1.7 on 2023-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
