# Generated by Django 4.1.7 on 2023-05-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_user_pin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
